attempt to make the CI rely on the code of crowdsec

diff --git a/.github/workflows/crowdsec-compat.yml b/.github/workflows/crowdsec-compat.yml
--- a/.github/workflows/crowdsec-compat.yml
+++ b/.github/workflows/crowdsec-compat.yml
@@ -8,26 +8,64 @@ on:
 
 jobs:
   build:
-    name: Hub/Crowdsec compatibility tests
+    strategy:
+      matrix:
+        csrelease: ["master", "v0.1.3", "v0.1.2"]
+    name: Hub/Crowdsec ${{matrix.csrelease}} compatibility tests
     runs-on: ubuntu-latest
     steps:
-    - name: fetch and extract release
+    - name: Set up Go 1.13
+      uses: actions/setup-go@v1
+      with:
+        go-version: 1.13
+      id: go
+    - name: Clone, build, setup crowdsec with all parsers
       run: |
-        wget https://github.com/crowdsecurity/crowdsec/releases/download/v0.1.3/crowdsec-release.tgz
-        mkdir crowdsec-release
-        tar xvzf crowdsec-release.tgz -C ./crowdsec-release --strip 1
-        cd crowdsec-release && ./test_env.sh
-        cd tests/
-    - name: fetch hub ci
-      working-directory: ./crowdsec-release/tests/
+        git clone https://github.com/crowdsecurity/crowdsec.git
+        cd crowdsec
+        git checkout ${csrelease}
+        make release
+        ls -l
+        cd crowdsec-pull
+        ./test_env.sh
+        cd tests
+        for i in `./cscli -c dev.yaml list parsers -a -o json | jq -r ".[].name" ` ; do 
+          ./cscli -c dev.yaml install parser $i ; 
+        done
+    - name: Clone and build hub CI
+      working-directory: ./crowdsec/
       run: |
         git clone https://github.com/crowdsecurity/hub-tests.git
-        cd hub-tests && bash -x ./prep_tests.sh && cd ..
-    - name: Run the tests
-      working-directory: crowdsec-release/tests/
+        cd hub-tests
+        make
+        cp ./main ../crowdsec-pull/tests/
+        cp -R ./tests ../crowdsec-pull/tests/
+    - name: Run the actual tests
+      working-directory: ./crowdsec/tests/
       run: |
         for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
-          echo "::group::Test-${i}" ; 
-          ./main $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail") ;
-          echo "::endgroup::" ;
+           echo "::group::Test-${i}" ; 
+           ./main $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail") ;
+           echo "::endgroup::" ;
         done ;
+
+    # - name: fetch and extract release
+    #   run: |
+    #     wget https://github.com/crowdsecurity/crowdsec/releases/download/${{matrix.csrelease}}/crowdsec-release.tgz
+    #     mkdir crowdsec-release
+    #     tar xvzf crowdsec-release.tgz -C ./crowdsec-release --strip 1
+    #     cd crowdsec-release && ./test_env.sh
+    #     cd tests/
+    # - name: fetch hub ci
+    #   working-directory: ./crowdsec-release/tests/
+    #   run: |
+    #     git clone https://github.com/crowdsecurity/hub-tests.git
+    #     cd hub-tests && bash -x ./prep_tests.sh && cd ..
+    # - name: Run the tests
+    #   working-directory: crowdsec-release/tests/
+    #   run: |
+    #     for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
+    #       echo "::group::Test-${i}" ; 
+    #       ./main $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail") ;
+    #       echo "::endgroup::" ;
+    #     done ;
