test updated hub ci

diff --git a/.github/workflows/crowdsec-compat.yml b/.github/workflows/crowdsec-compat.yml
--- a/.github/workflows/crowdsec-compat.yml
+++ b/.github/workflows/crowdsec-compat.yml
@@ -2,7 +2,7 @@ name: Hub-CI
 
 on:
   push:
-    branches: [ master ]
+    branches: [ master, test_ci ]
   pull_request:
     branches: [ master ]
 
@@ -10,7 +10,7 @@ jobs:
   build:
     strategy:
       matrix:
-        csrelease: ["v0.1.4", "v0.1.5"]
+        csrelease: ["v0.1.4", "v0.1.5", "0.2.0"]
     name: Hub/Crowdsec ${{matrix.csrelease}} compatibility tests
     runs-on: ubuntu-latest
     steps:
@@ -40,7 +40,7 @@ jobs:
       run: |
         for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
           echo "::group::Test-${i}" ; 
-          ./main $i || (echo "::error file=${i}::Failed test for ${i}, diff :" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail" ; sha256sum ${i}"/results.yaml" ; sha256sum ${i}"/results.yaml.fail"; exit 1) ;
+          ./main -c dev.yaml $i || (echo "::error file=${i}::Failed test for ${i}, diff :" ; diff ${i}"/results.json" ${i}"/results.json.fail" ; sha256sum ${i}"/results.json" ; sha256sum ${i}"/results.json.fail"; exit 1) ;
           echo "::endgroup::" ;
         done ;
 #upload artifacts in case of failure
