Update update-index.yml (#936)

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -80,13 +80,13 @@ jobs:
             #$1 is not quotted on purpose, so it can be expanded to multiple arguments
             aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths $1
           }
-          PATHS="/${{ env.version }}/.index.json"
-          IFS=',' read -ra FILE <<< "${{ env.changed_files }}"
-          for i in "${FILE[@]}"; do
-            PATHS="$PATHS /${{ env.version }}/$i"
-          done
-          echo "Invalidating paths: $PATHS"
+          # PATHS="/${{ env.version }}/.index.json"
+          # IFS=',' read -ra FILE <<< "${{ env.changed_files }}"
+          # for i in "${FILE[@]}"; do
+          #   PATHS="$PATHS /${{ env.version }}/$i"
+          # done
+          # echo "Invalidating paths: $PATHS"
           for ((i=0; i < 3; i++)); do
-            create_invalidation "$PATHS" && break || echo "Invalidation failed, retrying in 5 seconds..."
+            create_invalidation "/*" && break || echo "Invalidation failed, retrying in 5 seconds..."
             sleep 5
           done
