'mkindex' to eventually replace go code; check from CI that output is the same (#1208)
* 'mkindex' to eventually replace go code; check from CI that output is the same

* remove classification=null

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -30,7 +30,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/setup-go@v1
+      - uses: actions/setup-go@v5
         with:
           go-version: 1.19
       - uses: actions/checkout@v4
@@ -54,28 +54,54 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
-  
+
   run-linter:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: set up python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
       - name: checkout repo
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
           ref: ${{ github.ref }}
-      - name: install pipenv
-        run: |
-          python -m pip install --upgrade pip
-          pip install pipenv
+      - name: set up python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+          cache: 'pipenv'
       - name: install dependencies
         run: |
-          pipenv install --deploy --python 3.12
+          python -m pip install --upgrade pipenv wheel
+          pipenv install --deploy
       - name: hub linter
         run: |
           pipenv run ./hublint defaults > .hublint.toml
           pipenv run ./hublint check --color always --no-warning-details
+
+  run-mkindex:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.ref }}
+      - name: set up python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+          cache: 'pipenv'
+      - name: install dependencies
+        run: |
+          python -m pip install --upgrade pipenv wheel
+          pipenv install --deploy
+      - name: run mkindex
+        run: |
+          jq --sort-keys < .index.json >index.json
+          pipenv run ./mkindex >index-new.json
+          if ! (cmp -s index.json index-new.json); then
+              echo "Error: output from mkindex differs from legacy index builder."
+              diff -u index.json index-new.json
+              exit 1
+          fi
