proper invalidation

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -78,17 +78,17 @@ jobs:
           echo "changed_files=${changed_files}" >> $GITHUB_ENV
       - name: Invalidate cache
         run: |
-          # create_invalidation() {
-          #   #$1 is not quotted on purpose, so it can be expanded to multiple arguments
-          #   aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths $1
-          # }
-          # PATHS="/${{ env.version }}/.index.json"
-          # IFS=',' read -ra FILE <<< "${{ env.changed_files }}"
-          # for i in "${FILE[@]}"; do
-          #   PATHS="$PATHS /${{ env.version }}/$i"
-          # done
-          # echo "Invalidating paths: $PATHS"
+          create_invalidation() {
+            #$1 is not quotted on purpose, so it can be expanded to multiple arguments
+            aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths $1
+          }
+          PATHS="/${{ env.version }}/.index.json"
+          IFS=',' read -ra FILE <<< "${{ env.changed_files }}"
+          for i in "${FILE[@]}"; do
+            PATHS="$PATHS /${{ env.version }}/$i"
+          done
+          echo "Invalidating paths: $PATHS"
           for ((i=0; i < 3; i++)); do
-            aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths '/*' && break || echo "Invalidation failed, retrying in 5 seconds..."
+            create_invalidation "$PATHS" && break || echo "Invalidation failed, retrying in 5 seconds..."
             sleep 5
           done
