retry invalidation if it fails

diff --git a/.github/workflows/update-index.yml b/.github/workflows/update-index.yml
--- a/.github/workflows/update-index.yml
+++ b/.github/workflows/update-index.yml
@@ -77,8 +77,16 @@ jobs:
           echo "changed_files=${changed_files}" >> $GITHUB_ENV
       - name: Invalidate cache
         run: |
-          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/${{ env.version }}/.index.json"
+          create_invalidation() {
+            aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "$1"
+          }
+          PATHS="/${{ env.version }}/.index.json"
           IFS=',' read -ra FILE <<< "${{ env.changed_files }}"
           for i in "${FILE[@]}"; do
-            aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/${{ env.version }}/$i"
+            PATHS="$PATHS /${{ env.version }}/$i"
+          done
+          echo "Invalidating paths: $PATHS"
+          for ((i=0; i < 3; i++)); do
+            create_invalidation "$PATHS" && break || echo "Invalidation failed, retrying in 5 seconds..."
+            sleep 5
           done
